backend:
  name: github
  branch: main
  repo: inclusive-design/idrc-wcag-reporter
media_folder: src/assets/uploads
public_folder: /assets/uploads
editor:
  preview: false
collections:
  - label: Report
    name: report
    files:
      - label: About
        name: about
        file: src/_includes/about.md
        fields:
          - name: body
            label: About this report
            widget: markdown
      - label: Report Details
        name: report
        file: src/report/index.md
        fields:
          - label: Title
            name: title
            widget: string
          - name: "evaluators"
            label: "Evaluators"
            widget: "list"
          - name: "commissioner"
            label: "Commissioner"
            widget: "string"
          - name: targetLevel
            label: Target Level
            widget: select
            options: [A, AA, AAA]
          - name: targetWcagVersion
            label: Target WCAG Version
            widget: select
            options: ["2.0", "2.1", "2.2"]
          - name: date
            label: Date
            widget: datetime
          - name: specialRequirements
            label: Special Requirements
            widget: text
          - name: body
            label: Executive summary
            widget: markdown
          - name: scope
            label: In scope
            label_singular: in scope item
            widget: list
            fields:
              - {name: "title", label: "Title", widget: "string"}
              - {name: "url", label: "URL", widget: "string"}
              - {name: "description", label: "Description", widget: "text", required: false}
          - name: outOfScope
            label: Out of scope
            label_singular: out of scope item
            widget: list
            fields:
              - {name: "title", label: "Title", widget: "string"}
              - {name: "url", label: "URL", widget: "string"}
          - name: tools
            label: Tools used
            label_singular: tool
            widget: list
            summary: '{{fields.name}} {{fields.version}}'
            fields:
              - {name: "name", label: "Tool", widget: "string"}
              - {name: "version", label: "Version", widget: "string", required: false}
            hint: Enter browsers and assistive technologies used in auditing the website.
          - name: technologies
            label: Technologies used
            widget: list
            default: [HTML, CSS, JavaScript, WAI-ARIA, SVG]
            hint: Enter technologies used to build the website in a comma-separated list.
          - name: partiallySupported
            label: Partially Supported
            widget: relation
            multiple: true
            collection: report
            file: scData
            value_field: successCriteria.*.number
            search_fields: [successCriteria.*.number, successCriteria.*.name]
            display_fields: [successCriteria.*.number, successCriteria.*.name]
            required: false
          - name: unsupported
            label: Unsupported
            widget: relation
            multiple: true
            collection: report
            file: scData
            value_field: successCriteria.*.number
            search_fields: [successCriteria.*.number, successCriteria.*.name]
            display_fields: [successCriteria.*.number, successCriteria.*.name]
            required: false
          - name: issuesUrl
            label: Issues link
            widget: string
            hint: Enter the link to the website's GitHub repository or Gitlab repository.
            required: false
      - label: Success Criteria
        name: scData
        file: src/_data/scData.json
        editor:
          preview: false
        fields:
          - name: successCriteria
            label: Success Criteria
            summary: '{{fields.number}} {{fields.name}}'
            widget: list
            fields:
              - name: number
                label: Number
                widget: string
                readonly: true
              - name: name
                label: Name
                widget: string
  - label: Issues
    label_singular: Issue
    name: issue
    folder: src/report/issues
    extension: md
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - label: Success Criteria
        name: sc
        widget: relation
        multiple: true
        collection: report
        file: scData
        value_field: successCriteria.*.number
        search_fields: [successCriteria.*.number, successCriteria.*.name]
        display_fields: [successCriteria.*.number, successCriteria.*.name]
      - {label: Severity, name: severity, widget: select, options: ["Unknown", "Low", "Medium", "High"], required: false}
      - {label: Difficulty, name: difficulty, widget: select, options: ["Unknown", "Low", "Medium", "High"], required: false}
      - {label: Sample Pages, name: sample, widget: string, default: "all"}
      - {label: Screenshots, name: screenshots, widget: object, required: false, fields: [{label: "Screenshot", name: "src", widget: "image", required: false}, {label: "Alt Text", name: "alt", widget: "string", required: false}, {label: "Caption", name: "caption", widget: "text", required: false}]}
      - {label: Body, name: body, widget: markdown, default: "##### Problem\n\nDescribe the problem. Include code samples if necessary.\n\n##### Potential Solutions\n\nDescribe some potential solutions.\n\n##### Read more\n\nInclude some links to relevant examples and/or articles."}
