name: Merge dependency updates

on:
    workflow_run:
        types:
            - completed
        workflows:
            - 'Docker build'
            - 'Lint files'

jobs:
    merge-dependency-updates:
        name: Merge dependency updates
        runs-on: ubuntu-latest
        steps:
            - name: Merge dependency updates
              if: ${{ github.event.workflow_run.conclusion == 'success' }}
              uses: ridedott/merge-me-action@v2
              with:
                  # This must be used as GitHub Actions token does not support pushing
                  # to protected branches.
                  GITHUB_TOKEN: ${{ secrets.AUTO_MERGE_PR_TOKEN }}
                  PRESET: DEPENDABOT_MINOR
